feat: разработать согласно ТЗ-14 ShareIt
aigeley/java-shareit pull request #2
Opened 2022-10-28 13:23 UTC by aigeley

2022-10-28 16:43 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все отлично, все сущости описаны как надо, единственное я оставил нескольк вопросов по испоьзованию Optional, посмотри комментарии, пожалуйста :)

2022-10-28 16:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +        Optional.ofNullable(bookingDto.getId()).ifPresent(booking::setId);
Можно наверно было сделать и без Optional, NullPointerException не упала бы если бы поля были null, преобразований никаких же нет :)

2022-10-28 16:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryCustomImpl.java
> +        Specification<Booking> specification = Specification
Это API достаточно тяжелое для понимания, для простых случаев (методы выше) лучше его избегать, а вот тут вполне себе оправдано -  некоторое конструирование запросов в зависити от состояния :)

2022-10-28 16:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/model/CommentMapper.java
> +                comment.getItem().getId(),
Вот как раз тут и нужен Optional :)

Optiona.ofNullable(comment.getItem).map(Item::getId).orElse(null)

2022-10-28 16:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/model/UserMapper.java
> +        Optional.ofNullable(userDto.getId()).ifPresent(user::setId);
Я заметил в мапперах везде такая логика используется. В данном случае идет обновление не-null полей, так и положенно, то есть если поле в исходном объектое стало null, то оно не обновится в объекте-назначении(если там что то уже есть), это нормальное поведение? :)

2022-10-29 13:03 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +        Optional.ofNullable(bookingDto.getId()).ifPresent(booking::setId);
Исправлено, оставил Optional только там, где может быть частичное обновление полей через PATCH.

2022-10-29 13:03 UTC, aigeley commented on src/main/java/ru/practicum/shareit/item/model/CommentMapper.java
> +                comment.getItem().getId(),
Исправлено, добавил Optional везде, где запрашивается поле вложенного объекта.

2022-10-29 13:04 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryCustomImpl.java
> +        Specification<Booking> specification = Specification
Переписал ItemRepository::search на JPQL.
BookingRepositoryCustomImpl пока оставил как было, многие объявленные условия переиспользую повторно - могу ли в нём тоже как-то сократить запись?

2022-10-29 13:05 UTC, aigeley commented on src/main/java/ru/practicum/shareit/user/model/UserMapper.java
> +        Optional.ofNullable(userDto.getId()).ifPresent(user::setId);
Можем ли как-то в PATCH определить, что поле не было передано совсем (т.е. не нужно его обновлять) или что специально было передано значение field: null (нужно обновить поле на null)?
Так понял, выборочно обновить поля на null для существующего объекта можно, если заново передать объект целиком через PUT, но в ТЗ такого метода пока нет...

2022-10-29 16:06 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryCustomImpl.java
> +        Specification<Booking> specification = Specification
А вот там как раз пусть остается, там как раз используется повторно. Осоьо короче не уверен, главное чтобы понятно было что куда

2022-10-29 16:08 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/model/UserMapper.java
> +        Optional.ofNullable(userDto.getId()).ifPresent(user::setId);
Да не, не надо так заморачиваться, чтобы такое сделать потребуется переделать модель данных - пересылать непосрдественно список полей и уже их менять. У нас же приходит сущность, ее и обновляем, не думаю что тут стоит сильно усложнять логику, в большинстве случаев такого подхода достаточно :)

2022-10-29 16:08 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-10-29 18:28 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryCustomImpl.java
> +        Specification<Booking> specification = Specification
Попробую переписать в следующем спринте, спасибо!

2022-10-29 18:28 UTC, merged