feat: разработать согласно ТЗ-15 ShareIt
aigeley/java-shareit pull request #3
Opened 2022-11-23 15:35 UTC by aigeley

2022-11-24 06:24 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все отлично, пагинация на месте, сортировка в ней же 
Оставил небольшие пометки, посмотри пожалуйста комментарии ниже, толко про абстрактный класс - это скорее вопрос на подумать :)

2022-11-24 06:24 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingDtoMapper.java
> +public class BookingDtoMapper extends ElementDtoMapperAbs<Booking, BookingDto> {
Интересный подход, супер ;)

2022-11-24 06:24 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingWithEntitiesDtoMapper.java
> +        this.itemDtoMapper = itemDtoMapper;
Можно было тогда инжектить не через конструктор, а через @Autowired. было б покороче наверно, но это мелочи

@Autowired    
private ItemDtoMapper itemDtoMapper;
@Autowired
private UserDtoMapper userDtoMapper;

2022-11-24 06:24 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        PageRequestFromElement.of(from, size, Sort.by(Order.desc("id")))
А может этот кусочек в отдельный утилитарный метод, несколько раз встречается :)

Да и метод уже есть, несколько ниже в другом классе...
![image](https://user-images.githubusercontent.com/94845100/203708716-f5d9cf17-744f-4195-bbae-8d9b2abac883.png)

2022-11-24 06:24 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/element/model/ElementDtoMapper.java
> +    default List<D> toDtoList(List<E> elementList) {
Кстати, а что если тут сделать абстрактный класс
Дефолтные методы в интерфейсах по сути костыль, сделанный для обратной совместимости (так сделан в Java8новые методы в коллекциях, когда стримы появлялись). А в принципе то же самое реализуется через абстрактные классы, посмотри, может лучше так получится?

2022-11-24 12:01 UTC, aigeley commented on src/main/java/ru/practicum/shareit/element/model/ElementDtoMapper.java
> +    default List<D> toDtoList(List<E> elementList) {
Исправлено, перенёс всю реализацию в абстрактный класс ElementDtoMapperAbs

2022-11-24 12:04 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        PageRequestFromElement.of(from, size, Sort.by(Order.desc("id")))
Поправил, спрятал объявление сортировки в методы PageRequestFromElement.ofSortByIdAsc(from, size) и PageRequestFromElement.ofSortByIdDesc(from, size). Или нужно было по-другому сократить?

2022-11-24 15:26 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/model/BookingWithEntitiesDtoMapper.java
> +        this.itemDtoMapper = itemDtoMapper;
Поправил, заменил везде внедрение зависимостей через конструктор на внедрение через поля. Правда заметил, что в некоторых классах, где объявлен конструктор, Idea подчёркивает @Autowired и выводит предупреждение "Field injection is not recommended", можно на это не обращать внимания?

2022-11-24 19:14 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingWithEntitiesDtoMapper.java
> +        this.itemDtoMapper = itemDtoMapper;
Да везде то можно было и не делать, просто в том месте пришлось руками допоплнительно завиавимости покидывать в конструктор, можно было от этого так избавиться, я наверно не очень четко эту мысль описал :) 

А вообще это тема для холивара, вот например такая статья про это
https://habr.com/ru/post/334636/

2022-11-24 19:19 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-11-25 19:15 UTC, aigeley commented on src/main/java/ru/practicum/shareit/booking/model/BookingWithEntitiesDtoMapper.java
> +        this.itemDtoMapper = itemDtoMapper;
Понял, @RequiredArgsConstructor и сеттеры тоже буду иметь ввиду, спасибо!

2022-11-25 19:16 UTC, merged