feat: разработать согласно ТЗ-16 ShareIt
aigeley/java-shareit pull request #4
Opened 2022-12-07 19:53 UTC by aigeley

2022-12-08 05:09 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за присланное решение

В целом все супер, докер есть, валидация на гейтвее :)

С одной стороны кажется немного странным такое требование, но в этом есть своя логика: не дублировать проверки ибо, в будущем, проверки придется править в разных местах и рано или поздно это приведет к рассинхронизации реализаций и появлению множества багов, как следствие. А в микросервисах починка багов - это то еще приключение :)

Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API.
В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

Я подсветил один момент, посмотри, пожалуйста, может получится как то проще сделать :)

2022-12-08 05:09 UTC, eugene-lenkevich commented on server/src/main/java/ru/practicum/shareit/element/model/Identifiable.java
> +    default void setId(Long id) {
Мне кажется что еще можно сделать абстрактный класс с полем Id (+ get- и set- методы), как думаешь?
default-методы в интерфейсах добавили в 8ой java, чтобы прикрутить стримы к коллекциям, для обратной совместимости :)

Хотя, это холиварная тема
https://stackoverflow.com/questions/19998454/when-to-use-java-8-interface-default-method-vs-abstract-method

2022-12-08 13:56 UTC, aigeley commented on server/src/main/java/ru/practicum/shareit/element/model/Identifiable.java
> +    default void setId(Long id) {
Поправил, заменил на абстрактный класс Element

2022-12-08 14:03 UTC, aigeley commented
> Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API. В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

Евгений, добрый день!
Подскажи, пожалуйста, правильно понял, что можно в gateway сразу подключать классы DTO из server, что бы не было дублирования?
Спасибо!

2022-12-08 14:51 UTC, eugene-lenkevich commented
> правильно понял, что можно в gateway сразу подключать классы DTO из server, что бы не было дублирования?

Привет!
Если коротко - это не дублирование 

Если развернуто, как раз недавно кому то отвечал на аналогичный вопрос  :)

Вообще если загуглить "sharing dto between microservices" то можно увидеть огромное количество обсуждений на эту тему
https://stackoverflow.com/questions/1440952/why-are-data-transfer-objects-dtos-an-anti-pattern

Для начала надо понять проблематику  


Предположим у нас есть автосалон. У нас есть модель - автомобиль. У нас есть несколько отделов (читай учетных систем) которые работают c этой моделью. Вроде все логично, все просто, но не совсем - в каждом отделе модель на самом деле разная (разный набор атрибутов и связанных сущностей): в отделе продаж (цена комплектация м пр), на СТО (уровень масла, пробег и тд), допустим кредитный отдел - залоговая стоимость и доход клиента. 

Допустим у нас монолит.  Тогда у нас в БД будет огромное количество таблиц, которое покрывает требования всех отделов, куча кода и связей. 

Если у нас микросервис, например сделанный из этого монолита. У нас есть одна модель, мы ее выделяем в библиотеку. И теперь, при каждом изменении модели мы будем вынуждены менять все сервисы, иначе, в случае неактуальной модели в одном из них, мы получим несоответствие. Таким образом, мы получаем распределеннывй монолит - все самое плохое и от монолитов и от микросервисов. 

Чтобы этого избежать делают следующее: каждый микросервис имеет свою модель, свой автомобиль со своими полями. Тут нам надо сослаться на DDD (domain driven design)
https://ru.wikipedia.org/wiki/Предметно-ориентированное_проектирование

Причем если, грубо говоря, в двух сервисах dto совпадают, то это не дублирование кода, это просто в данный момент совпадает реализация и их не надо объединять в один модуль. Соотвественно, изменения в одном сервисе касаются только его одного. Так мы делаем наши сервисы независимыми. Если одному сервису надо узнать информацию из модели из другого, он делает http-запрос (или через асинхронные сообщения), получает JSON (или еще какой то формат, не важно), парсит его и берет нужные поля. Чтобы упростить этот парсинг и исключить несоответствия именно в контактах мы импортируем клиентскую библиотеку того сервиса, парсим в его же dto и, далее, перекладываем уже в локальную модель, например.

То есть имеет смысл выделить в отдельную библиотеку только контракты, то есть те dto и интерфейсы, чрез которые идет коммуникация с этим модулем
Примерно так пакеты будут выглядеть
- gateway (со своими dto)
- server
- - server-api (тут наши dto для экспорта данных)
- - server-src (тут наши внутренние dto и сама модель)

2022-12-08 15:54 UTC, eugene-lenkevich approved these changes
Привет, спасибо за доработку

В абстрактный класс можно было перенести и сам id :)

private Long id;

Ладно, это мелочи, все гут

2022-12-09 09:35 UTC, aigeley commented
> То есть имеет смысл выделить в отдельную библиотеку только контракты, то есть те dto и интерфейсы, чрез которые идет коммуникация с этим модулем

Понял, попробую реализовать, спасибо!

> В абстрактный класс можно было перенести и сам id :)

Для обогащения расширенных DTO создал дополнительные расширенные модели, с вложенными в поля простыми моделями - получается, что у них нет отдельного поля id, например, в ItemWithBookings достаю id из вложенного объекта item.getId() - или лучше не делать вложенные объекты и расширенные модели тоже собирать из простых параметров? На будущее тогда буду иметь ввиду.
Спасибо!

2022-12-09 10:49 UTC, eugene-lenkevich commented
> Для обогащения расширенных DTO создал дополнительные расширенные модели, с вложенными в поля простыми моделями - получается, что у них нет отдельного поля id, например, в ItemWithBookings достаю id из вложенного объекта item.getId() 

Тогда не, тогда норм  :)

2022-12-09 11:49 UTC, merged